apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: mlops-api-pod-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: mlops-api    # ðŸ‘ˆ Debe coincidir con tu Deployment
  endpoints:
    - port: metrics     # ðŸ‘ˆ Debe coincidir con name: metrics en el Deployment
      path: /metrics
      interval: 30s
