apiVersion: v1
kind: Service
metadata:
  name: mlops-telco-web-service
spec:
  type: LoadBalancer
  selector:
    app: mlops-telco-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8502
