apiVersion: v1
kind: Service
metadata:
  name: mlops-telco-api-service
spec:
  selector:
    app: mlops-telco-api
  ports:
    - name: http
      protocol: TCP
      port: 5001        # puerto interno del Service
      targetPort: 5001  # puerto del contenedor
  type: ClusterIP       # solo dentro del cl√∫ster
